### PR TITLE
[Feature] Refer to the English version (PDF) in README

### PR DESCRIPTION
**Pull request by bardancing985**
Currently some visitors (including me) fail to find an English version at their first glance, while actually there's just one lying under this very repo. 

This commit adds a reference to this bundled English version (a PDF file) at the beginning of README.

### CODE REVIEW

**Comment by mffseal** [comment]
nice bro.

**Comment by cjyayy** [comment]
good job，let the world see it！

**Comment by mogicianhabsbury** [comment]
主主主

**Review by MoeBuTa — APPROVED** [review]

**Review by alpc66 — APPROVED** [review]
LGTM, thank you for your contribution! Looks good to me

**Review by Sephiroth42 — APPROVED** [review]

**Review by zhimin-z — APPROVED** [review]

**Review by lazy-forever — APPROVED** [review]

**Review by HuanzhiMao — APPROVED** [review]
good job

**Comment by KNKNKNL** [comment]
LGTM

**Review by KNKNKNL — APPROVED** [review]

**Review by ExplodingDragon — APPROVED** [review]
LGTM 

Maybe we can use GitHub CI to create GitHub Pages?

**Review by Linchen-Xu — APPROVED** [review]

**Review by fishtailstudio — APPROVED** [review]

**Comment by HansongYan666** [comment]
newbee！

**Comment by elin-croft** [comment]
建议写一个英文版的readme，然后在其中附上pdf，避免github加载pdf异常

**Review by elin-croft — APPROVED** [review]

**Review by Wajorrr — APPROVED** [review]

**Comment by fish4terrisa-MSDSM** [comment]
看来已经增加了英语版了(笑
这盛世 如你所愿 XD

**Review by enpitsuLin — APPROVED** [review]

**Review by AnkorTn — APPROVED** [review]
Nice

**Review by YuetianW — APPROVED** [review]

**Comment by stardow1022** [comment]
LGTM

**Review by stardow1022 — APPROVED** [review]

**Comment by JiaweiZhang1997** [comment]
LGTM

**Review by childrentime — APPROVED** [review]
LGTM👍🏿

**Review by namasikanam — APPROVED** [review]
LGTM

**Review by haichao2023 — APPROVED** [review]
LGTM

**Comment by Therm4l** [comment]
最符合现实的一集：一稿多投，中英互译👍

**Review by dclcs — APPROVED** [review]

**Review by taro0513 — APPROVED** [review]
LGTM!!

**Review by GithubX-F — APPROVED** [review]

**Comment by bardancing985** [comment]
The README file has been updated, so this PR is no longer necessary.

**Pull request closed without merging**
