### PR TITLE
Add category and citation to help read

### PR DESCRIPTION
**Pull request by xrkong**
This article is a bit long, so I added a table of contents to help readers quickly jump to the parts they are interested in. I also added a bibtex citation format at the end.

### CODE REVIEW

**Comment by ESUAdmin** [comment]
TOC is unnecessary because of

this :rofl:

**Comment by KaysinBIT** [comment]
very goooooooooooooooooooooooooodd job brooooooooooooo

**Review by elin-croft — APPROVED** [review]

**Comment by elin-croft** [comment]
xiexie u! my hao bro

**Review by zhimin-z — APPROVED** [review]

**Comment by stardow1022** [comment]
非常好添加，使我任务旋转

**Review by BarryAlllen — APPROVED** [review]

**Review by sweetning0809 — APPROVED** [review]
LGTM

**Review by KNKNKNL — APPROVED** [review]

**Review by MoeBuTa — APPROVED** [review]
LGTM

**Review by Linchen-Xu — APPROVED** [review]

**Review by liuup — APPROVED** [review]

**Review by nightt5879 — APPROVED** [review]

**Review by GalaxyHBXY — APPROVED** [review]

**Review by NestorLiao — APPROVED** [review]

**Comment by gudong1012** [comment]
thanks

**Review by AntiO2 — APPROVED** [review]

**Pull request closed without merging**
